# Generated by Django 3.2.17 on 2025-01-21 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extra User Info',
                'verbose_name_plural': 'Extra Users Info',
            },
        ),
    ]
